name: Push to GitHub Container Registry

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract repository name
        run: echo "REPOSITORY_NAME=${GITHUB_REPOSITORY#*/}" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ghcr.io/${{ github.repository }}/${{ env.REPOSITORY_NAME }}:${{ github.sha }}
          context: ./simplechat
          file: ./simplechat/Dockerfile

      # - name: Build and push Docker image with datetime tag
      #   run: |
      #     DATE_TAG=$(date -u +'%Y%m%d%H%M%S')
      #     docker build -t ghcr.io/${{ github.repository }}/${{ env.REPOSITORY_NAME }}:$DATE_TAG .
      #     docker push ghcr.io/${{ github.repository }}/${{ env.REPOSITORY_NAME }}:$DATE_TAG

